version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi_app_dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "
      aerich init -t tortoise_config.TORTOISE_ORM || true &&
      aerich init-db || true &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev

  db:
    image: postgres:15-alpine
    container_name: fastapi_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
