# Use the official Python image as base
FROM python:3.11-slim

# Set working directory
WORKDIR /usr/src/app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

# Set environment variables (or use env_file in docker-compose)
ENV PYTHONUNBUFFERED=1

# Define default command for the celery worker
CMD ["sh", "-c", "wait-for-it.sh rabbitmq:5672 --timeout=60 --strict && celery -A app.celery_worker.celery_app worker --loglevel=info"]
