version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_app_prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
